# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e13e84809e22ce2da676e7602ea22488ab886ee7aec7417799cb5830a58fd5d22ceb0c7d96f5f724facbe3c554f0ac90da84f9de8f6135aea8d2c547a507fac

test:
  secret_key_base: e2baeb7ac693358a0457b4e5f1f230ebf5f6e09910ee539d038b13b834603ac89f0e932f27357109a233e7b0122d83d05fc70fdcfefe0c2a94daba9427cd6f06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
